name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run PyLint
        run: |
          pylint *  --disable=C0103,C0303,W0621,W0221,R0402,C0114 --ignore=timeseries_dataset.py,README.md --exit-zero > pylint.txt
      - name: Check PyLint score
        run: |
          SCORE=$(cat pylint.txt | grep "Your code has been rated at" | awk '{print $7}' | cut -f1 -d/)
          if [ "$SCORE" -ge 9 ]; then
            echo "PyLint check passed"
          else
            echo "PyLint check failed with score $SCORE"
            exit 1
          fi
